import { TransactionTypeEnum, type Transaction } from "../types";

export const mockTransactions: Transaction[] = [
  // October
  {
    id: "t001",
    date: "2025-10-11",
    amount: 85000,
    category: "Income",
    type: TransactionTypeEnum.Income,
    description: "Monthly Salary",
    merchant: "TechCorp India",
  },
  {
    id: "t002",
    date: "2025-10-13",
    amount: 4200,
    category: "Food & Dining",
    type: TransactionTypeEnum.Expense,
    description: "Grocery shopping",
    merchant: "Big Bazaar",
  },
  {
    id: "t003",
    date: "2025-10-15",
    amount: 1800,
    category: "Transport",
    type: TransactionTypeEnum.Expense,
    description: "Uber rides",
    merchant: "Uber",
  },
  {
    id: "t004",
    date: "2025-10-18",
    amount: 12000,
    category: "Housing",
    type: TransactionTypeEnum.Expense,
    description: "Monthly rent",
    merchant: "Landlord",
  },
  {
    id: "t005",
    date: "2025-10-20",
    amount: 2500,
    category: "Shopping",
    type: TransactionTypeEnum.Expense,
    description: "Clothes",
    merchant: "Myntra",
  },
  {
    id: "t006",
    date: "2025-10-23",
    amount: 5000,
    category: "Investments",
    type: TransactionTypeEnum.Income,
    description: "Mutual fund returns",
    merchant: "Zerodha",
  },
  {
    id: "t007",
    date: "2025-10-26",
    amount: 900,
    category: "Entertainment",
    type: TransactionTypeEnum.Expense,
    description: "Netflix & Spotify",
    merchant: "Netflix",
  },
  {
    id: "t008",
    date: "2025-10-28",
    amount: 3200,
    category: "Health",
    type: TransactionTypeEnum.Expense,
    description: "Gym membership",
    merchant: "Cult.fit",
  },
  {
    id: "t009",
    date: "2025-10-30",
    amount: 650,
    category: "Utilities",
    type: TransactionTypeEnum.Expense,
    description: "Electricity bill",
    merchant: "BSES",
  },
  {
    id: "t010",
    date: "2025-11-02",
    amount: 1600,
    category: "Food & Dining",
    type: TransactionTypeEnum.Expense,
    description: "Restaurant dinners",
    merchant: "Swiggy",
  },
  {
    id: "t011",
    date: "2025-11-05",
    amount: 4500,
    category: "Education",
    type: TransactionTypeEnum.Expense,
    description: "Online course",
    merchant: "Udemy",
  },

  // November
  {
    id: "t012",
    date: "2025-11-11",
    amount: 85000,
    category: "Income",
    type: TransactionTypeEnum.Income,
    description: "Monthly Salary",
    merchant: "TechCorp India",
  },
  {
    id: "t013",
    date: "2025-11-13",
    amount: 3800,
    category: "Food & Dining",
    type: TransactionTypeEnum.Expense,
    description: "Grocery shopping",
    merchant: "DMart",
  },
  {
    id: "t014",
    date: "2025-11-16",
    amount: 2100,
    category: "Transport",
    type: TransactionTypeEnum.Expense,
    description: "Metro & Cab",
    merchant: "Ola",
  },
  {
    id: "t015",
    date: "2025-11-18",
    amount: 12000,
    category: "Housing",
    type: TransactionTypeEnum.Expense,
    description: "Monthly rent",
    merchant: "Landlord",
  },
  {
    id: "t016",
    date: "2025-11-22",
    amount: 3500,
    category: "Shopping",
    type: TransactionTypeEnum.Expense,
    description: "Valentine's gifts",
    merchant: "Amazon",
  },
  {
    id: "t017",
    date: "2025-11-24",
    amount: 8000,
    category: "Investments",
    type: TransactionTypeEnum.Income,
    description: "Dividend income",
    merchant: "HDFC Sec",
  },
  {
    id: "t018",
    date: "2025-11-26",
    amount: 1200,
    category: "Entertainment",
    type: TransactionTypeEnum.Expense,
    description: "Movie tickets",
    merchant: "BookMyShow",
  },
  {
    id: "t019",
    date: "2025-11-28",
    amount: 850,
    category: "Utilities",
    type: TransactionTypeEnum.Expense,
    description: "Internet bill",
    merchant: "ACT",
  },
  {
    id: "t020",
    date: "2025-12-02",
    amount: 2200,
    category: "Health",
    type: TransactionTypeEnum.Expense,
    description: "Doctor visit",
    merchant: "Apollo Clinic",
  },
  {
    id: "t021",
    date: "2025-12-04",
    amount: 5500,
    category: "Travel",
    type: TransactionTypeEnum.Expense,
    description: "Weekend trip",
    merchant: "MakeMyTrip",
  },

  // December
  {
    id: "t022",
    date: "2025-12-09",
    amount: 92000,
    category: "Income",
    type: TransactionTypeEnum.Income,
    description: "Monthly Salary + Bonus",
    merchant: "TechCorp India",
  },
  {
    id: "t023",
    date: "2025-12-11",
    amount: 4600,
    category: "Food & Dining",
    type: TransactionTypeEnum.Expense,
    description: "Grocery + Holi sweets",
    merchant: "Big Bazaar",
  },
  {
    id: "t024",
    date: "2025-12-14",
    amount: 1500,
    category: "Transport",
    type: TransactionTypeEnum.Expense,
    description: "Cab rides",
    merchant: "Rapido",
  },
  {
    id: "t025",
    date: "2025-12-16",
    amount: 12000,
    category: "Housing",
    type: TransactionTypeEnum.Expense,
    description: "Monthly rent",
    merchant: "Landlord",
  },
  {
    id: "t026",
    date: "2025-12-18",
    amount: 6200,
    category: "Shopping",
    type: TransactionTypeEnum.Expense,
    description: "Holi shopping",
    merchant: "Flipkart",
  },
  {
    id: "t027",
    date: "2025-12-21",
    amount: 10000,
    category: "Investments",
    type: TransactionTypeEnum.Income,
    description: "SIP maturity",
    merchant: "Groww",
  },
  {
    id: "t028",
    date: "2025-12-23",
    amount: 750,
    category: "Entertainment",
    type: TransactionTypeEnum.Expense,
    description: "Gaming subscription",
    merchant: "Steam",
  },
  {
    id: "t029",
    date: "2025-12-26",
    amount: 1100,
    category: "Utilities",
    type: TransactionTypeEnum.Expense,
    description: "Water & Gas",
    merchant: "IGL",
  },
  {
    id: "t030",
    date: "2025-12-28",
    amount: 1800,
    category: "Health",
    type: TransactionTypeEnum.Expense,
    description: "Medicines",
    merchant: "PharmEasy",
  },
  {
    id: "t031",
    date: "2026-01-03",
    amount: 7500,
    category: "Travel",
    type: TransactionTypeEnum.Expense,
    description: "Holi trip home",
    merchant: "IRCTC",
  },

  // January
  {
    id: "t032",
    date: "2026-01-08",
    amount: 85000,
    category: "Income",
    type: TransactionTypeEnum.Income,
    description: "Monthly Salary",
    merchant: "TechCorp India",
  },
  {
    id: "t033",
    date: "2026-01-10",
    amount: 3900,
    category: "Food & Dining",
    type: TransactionTypeEnum.Expense,
    description: "Groceries",
    merchant: "Zepto",
  },
  {
    id: "t034",
    date: "2026-01-13",
    amount: 2000,
    category: "Transport",
    type: TransactionTypeEnum.Expense,
    description: "Monthly metro pass",
    merchant: "DMRC",
  },
  {
    id: "t035",
    date: "2026-01-15",
    amount: 12000,
    category: "Housing",
    type: TransactionTypeEnum.Expense,
    description: "Monthly rent",
    merchant: "Landlord",
  },
  {
    id: "t036",
    date: "2026-01-17",
    amount: 4100,
    category: "Shopping",
    type: TransactionTypeEnum.Expense,
    description: "Summer clothes",
    merchant: "H&M",
  },
  {
    id: "t037",
    date: "2026-01-20",
    amount: 6000,
    category: "Investments",
    type: TransactionTypeEnum.Income,
    description: "Freelance project",
    merchant: "Toptal",
  },
  {
    id: "t038",
    date: "2026-01-22",
    amount: 980,
    category: "Entertainment",
    type: TransactionTypeEnum.Expense,
    description: "OTT subscriptions",
    merchant: "Prime Video",
  },
  {
    id: "t039",
    date: "2026-01-25",
    amount: 720,
    category: "Utilities",
    type: TransactionTypeEnum.Expense,
    description: "Electricity",
    merchant: "BSES",
  },
  {
    id: "t040",
    date: "2026-01-29",
    amount: 3500,
    category: "Education",
    type: TransactionTypeEnum.Expense,
    description: "Design workshop",
    merchant: "Skillshare",
  },

  // February
  {
    id: "t041",
    date: "2026-02-07",
    amount: 85000,
    category: "Income",
    type: TransactionTypeEnum.Income,
    description: "Monthly Salary",
    merchant: "TechCorp India",
  },
  {
    id: "t042",
    date: "2026-02-10",
    amount: 5100,
    category: "Food & Dining",
    type: TransactionTypeEnum.Expense,
    description: "Groceries & dining out",
    merchant: "Zomato",
  },
  {
    id: "t043",
    date: "2026-02-13",
    amount: 1700,
    category: "Transport",
    type: TransactionTypeEnum.Expense,
    description: "Cab & fuel",
    merchant: "Uber",
  },
  {
    id: "t044",
    date: "2026-02-15",
    amount: 12000,
    category: "Housing",
    type: TransactionTypeEnum.Expense,
    description: "Monthly rent",
    merchant: "Landlord",
  },
  {
    id: "t045",
    date: "2026-02-17",
    amount: 14500,
    category: "Travel",
    type: TransactionTypeEnum.Expense,
    description: "Goa trip",
    merchant: "GoIbibo",
  },
  {
    id: "t046",
    date: "2026-02-20",
    amount: 7500,
    category: "Investments",
    type: TransactionTypeEnum.Income,
    description: "Stock profits",
    merchant: "Zerodha",
  },
  {
    id: "t047",
    date: "2026-02-23",
    amount: 2800,
    category: "Shopping",
    type: TransactionTypeEnum.Expense,
    description: "Electronics",
    merchant: "Croma",
  },
  {
    id: "t048",
    date: "2026-02-27",
    amount: 900,
    category: "Utilities",
    type: TransactionTypeEnum.Expense,
    description: "Bills",
    merchant: "Paytm",
  },
  {
    id: "t049",
    date: "2026-03-03",
    amount: 1500,
    category: "Health",
    type: TransactionTypeEnum.Expense,
    description: "Annual checkup",
    merchant: "Max Hospital",
  },

  // March/April
  {
    id: "t050",
    date: "2026-03-10",
    amount: 85000,
    category: "Income",
    type: TransactionTypeEnum.Income,
    description: "Monthly Salary",
    merchant: "TechCorp India",
  },
  {
    id: "t051",
    date: "2026-03-13",
    amount: 4300,
    category: "Food & Dining",
    type: TransactionTypeEnum.Expense,
    description: "Groceries",
    merchant: "Big Basket",
  },
  {
    id: "t052",
    date: "2026-03-15",
    amount: 1600,
    category: "Transport",
    type: TransactionTypeEnum.Expense,
    description: "Metro & Ola",
    merchant: "Ola",
  },
  {
    id: "t053",
    date: "2026-03-18",
    amount: 12000,
    category: "Housing",
    type: TransactionTypeEnum.Expense,
    description: "Monthly rent",
    merchant: "Landlord",
  },
  {
    id: "t054",
    date: "2026-03-21",
    amount: 3200,
    category: "Shopping",
    type: TransactionTypeEnum.Expense,
    description: "Monsoon shopping",
    merchant: "Myntra",
  },
  {
    id: "t055",
    date: "2026-03-24",
    amount: 5500,
    category: "Investments",
    type: TransactionTypeEnum.Income,
    description: "Mutual fund returns",
    merchant: "Groww",
  },
  {
    id: "t056",
    date: "2026-03-26",
    amount: 850,
    category: "Entertainment",
    type: TransactionTypeEnum.Expense,
    description: "Movies & games",
    merchant: "BookMyShow",
  },
  {
    id: "t057",
    date: "2026-03-29",
    amount: 680,
    category: "Utilities",
    type: TransactionTypeEnum.Expense,
    description: "Electricity",
    merchant: "BSES",
  },
  {
    id: "t058",
    date: "2026-04-02",
    amount: 2100,
    category: "Health",
    type: TransactionTypeEnum.Expense,
    description: "Dental checkup",
    merchant: "Dental Care",
  },
  {
    id: "t059",
    date: "2026-04-05",
    amount: 4800,
    category: "Other",
    type: TransactionTypeEnum.Expense,
    description: "Miscellaneous",
    merchant: "Various",
  },
];



